### ISSUE TITLE
d2Common assertion error.

### ISSUE THREAD

**Issue by Moonpaw** [zyel/zyel#2] opened 2015-10-25 00:07 UTC
Hello, i downloaded the latest/newest version from github. zy el -master and when i try to run it and load a char i get an assertion error from d2common. I havent even made changes yet

**Comment by xmontex** [comment] 2015-10-25 22:04
Hi, I did not expect anyone to download it... Got bored with the original 4.4 version so decided to mess with 4.5 again. Its mostly for my own entertainment.
I play the "standalone" version (not D2SE). D2Game.dll, D2Common.dll, d2mod.dll, d2modsetup.exe should be copied from zyel folder to d2 root folder (and then run d2modsetup once). Backup original dlls first. 
I have brought back some of the original features (mostly quest rewards) with dll changes + some bug fixes (socketed thrown prices and merc exp limits). No errors for me when i try to launch the game. Send me the error log if nothing helps.
One of the the more important changes worth to mention is the /players x command. Maximum number was reduced back to 8 (from 127) but the monsters on current p8 are as strong as they were on old 127. This was mostly done to get rid of full screen of loot i used to get on p8. The loot quantity wasnt reduced yet now players would need to struggle to earn that loot. Im still playing act 1 myself p1 - p3. p8 still looks quite scary.
Other commits are mostly small changes

**Comment by Moonpaw** [comment] 2015-10-27 03:12
all i want is a version where the data bin files are decrypted in txt files so i can mod myself. but the latest github version i can copy from here isnt playable, cause of crashes, with above error

**Comment by xmontex** [comment] 2015-11-15 10:24
since there is no additional info i will assume that it was duplicate of #6

**Closed as completed by xmontex** 2015-11-15 10:24 UTC
